### ISSUE TITLE
Repo missing powershell script

### ISSUE THREAD

**Issue by patrickryan79** [BrianMikinski/vuessl#1]
Came across this: https://www.briangetsbinary.com/vue/software%20engineering/2022/10/09/vue-js-configuring-localhost-ssl.html

Where is the powershell script? Thank you!

**Comment by BrianMikinski** [comment]
@patrickryan79 - it's missing! I'll get it added asap!

**Comment by BrianMikinski** [comment]
@patrickryan79 

Powershell file has been added to the repo. Thanks again for pointing this out!
